Social Login and Unit Test Complete
wecode-bootcamp-korea/45-2nd-headbanger-backend pull request #12
Opened 2023-05-25 12:06 UTC by innichang

## 1. 본 PR이 우리 팀의 웹 서비스 제품성에 어떠한 기여를 하였고, 사용자에게 어떠한 기대효과를 전달하는지 작성해주세요.
- 내 PR이 제품 내 어떠한 기능적인 배경/전후맥락 가운데 개발되었나요?

유저들에게 여러가지 경로의 회원가입 방법을 주어서, 조금 더 편한 마음으로 회원가입/로그인을 진행 할 수 있는 시간을 주고 싶었습니다. 저희 사이트에게 직접적으로 제공되는 방법과, 카카오 소셜 로그인을 통해, 카카오에서 서버가 정보를 받아오는 두가지 방식이 있습니다.
또한, 발생되는 광고나, 회원가입/로그인 플로우에 방해가 될만한 요소들을 제거함으로, 이탈율을 줄였습니다.

- 내 PR이 Merge 됨으로써 유저에게 전달되는 편익/기대효과는 무엇일까요?

로그인과 회원가입은 유저들이 사이트를 사용하기전에, 조금 더 편하게 사용하기 위해서, 민감한 정보들을 사이트에게 전달할때입니다. 
그러므로 조금 더 확실히, 매번 확인하는 flow로 API를 설계해, 오류를 최소화 하기 위해 노력했습니다. 

또한, 모두 완료된 unit test를 통해 코드의 견고함을 한층 강화해서 유저들이 안전하게 로그인과 회원가입 플로우를 탈 수 있게 됩니다. 

<br />

## 2. 이 브랜치에서 어떤 내용을 개발했는지 큰 제목과 그리고 상세 내역을 적어주세요.

[이메일 확인 기능 추가]
- 이메일 유효성 검사
- 이메일 존재 여부 검사
false -> 회원가입, true -> 로그인

[회원가입 기능 추가]
- 이메일, 비밀번호 유효성 검사
- 비밀번호 암호화하여 DB저장

[로그인 기능 추가]
- 이메일, 비밀번호 유효성 검사
- 암호화된 비밀번호 bcrypt.compare로 입력된 암호화 비교
- JWT 발급

[소셜 로그인 기능 추가]
- 클라이언트에서 access_token을 받아와 카카오 서버와 통신
- 유저 정보 가져와서, 존재 여부 검사
false -> 회원가입 -> 토큰 발송
true -> 토큰 발송

<br />

## 3. 이 브랜치에서 개발하면서 느꼇던 개발 성장포인트를 적어주세요.

- unit test에 대한 이해도가 늘었습니다.
- OAuth의 flow를 공부하고, 그것을 코드에 적용시켜 보았습니다.

2023-05-25 14:38 UTC, kyeongraekim requested changes

2023-05-25 14:38 UTC, kyeongraekim commented on src/routes/index.js
> +>>>>>>> e11772f (WIP)
- 이곳 Conflict 해결이 잘못 되어있는 것 같네요  한 번 확인 부탁드려요!~

2023-05-25 14:38 UTC, kyeongraekim commented on package.json
> +    "g": "^2.0.1",
- 해당 패키지는 사용을 하는 패키지일까요? 다시 한 번 확인 부탁드립니다!

2023-05-25 14:38 UTC, kyeongraekim commented on package.json
> +    "node-fetch": "^3.3.1",
- 해당 패키지도 사용을 하지 않고 있는데, 해당 패키지에 있는 것 같아 보이네요! 한 번 확인부탁드려요!~

2023-05-25 14:38 UTC, kyeongraekim commented on src/controllers/userController.js
> +  return res.status(400).json({ message: 'FAILED TO SIGN UP' });
- 이곳에서 까지 if 조건을 걸어 signUp의 에러메세지를 담을 필요는 없어보입니다. 
- 위 키에러와 유효성 검사를 맞춘 내용에 대한 데이터 값이 에러를 낸다면 결국 DAO 가 내뱉는 에러가 에러의 주체가 될 것이기 때문이죠!

2023-05-25 14:38 UTC, kyeongraekim commented on src/controllers/userController.js
> +  const { access_token } = req.body;
- 변수명을 snake_case가 아닌 camelCase로 바꾸어서 수정해주세요!

2023-05-25 14:38 UTC, kyeongraekim commented on src/models/userDao.js
> +    console.log('checkUserByKakaoId ', user);
-  불필요한 콘솔로깅을 삭제해주세요!!

2023-05-25 14:38 UTC, kyeongraekim commented on src/models/userDao.js
> +  console.log(user.insertId);
- 이곳도 불필요한 콘솔로깅을 삭제해주세요!
- main으로의 푸시 전에 꼼꼼히 살피신 후 올려주심을 잊지말아주세요!

2023-05-25 14:38 UTC, kyeongraekim commented on src/services/userService.js
> +    const kakaoName = kakaoResult.data.properties.nickname;
- 해당 내용은 nested 구조분해 할당을 통해서 한 번에 모든 내용을 얻어올 수 있습니다. 아래구조를 한 번 참고해보세요!

```javascript
  const {
    id: kakaoId,
    properties: { nickname: nickname, profile_image: profileImage },
    kakao_account: { email, birthday, gender, age_range: ageRange },
  } = response.data;

2023-05-25 14:38 UTC, kyeongraekim commented on src/models/userDao.js
> +};
- Select 1 이 중간에 들어가는 표현이 흔히 쓰이는 방법이기는하나, 가독성에서 조금은 아쉽지 않을까 하는 생각이 있습니다. 
- 그리고 해당 내용에서 false / true의 리턴을 바로한다면 서비스단에서 if-else 분기를 조금 줄여볼 수 있을 것 같네요!!
- 아래 내용을 응용하고 참고해보세요!

```javascript
const checkRegisterdEmail = async (email) => {
  const [result] = await appDataSource.query(
    `SELECT EXISTS(
          SELECT
          id
        FROM
          users
        WHERE
          email=?
      ) as registed`,
    [email]
  );
  return !!parseInt(result.registed);
};

2023-05-25 14:38 UTC, kyeongraekim commented on src/models/userDao.js
> +const fetchPassword = async (email) => {
- fetchPassword 보다 getUserPasswordByEmail 정도로 수정이 가능하겠네요.
- 하지만 가만히 생각해보면, getUserByEmail 과 같이 유저 테이블의 모든 데이터를 범용적으로 끌고오는 모듈이 하나 있다면 해당 내용에서 패스워드를 끌고올 수 있겠네요!

2023-05-25 14:38 UTC, kyeongraekim commented on tests/user.test.js
> +
- 팀 동료인 지은님은 fixture, 데이터의 모듈화 등을 이용해 테스트코드에서 활용하고 있습니다. 
- 한 팀의 코드는 모두 동일한 모습을 띄어아햘 당위성이 있습니다. 마치 하나의 글에서 서로 다른 문장형식의 문체를 쓰게되면 어색해지는 것과 비슷한 이치입니다.
- 따라서 테스트 데이터 베이스에 목데이터를 넣는 행위를 지은님 코드와 동일시하게 리팩토링하여 재푸시해주세요!

2023-05-26 00:03 UTC, innichang commented on package.json
> +    "g": "^2.0.1",
어찌 들어간건지 모르겠지만, 삭제하였습니다.

2023-05-26 00:04 UTC, innichang commented on package.json
> +    "node-fetch": "^3.3.1",
처음엔 axios 대신node-fetch를 install해서 fetch method를 사용하려고 해서 install했었습니다. 하지만 사용하지 않는 관계로 삭제 조치하겠습니다.

2023-05-26 00:06 UTC, innichang commented on src/controllers/userController.js
> +  const { access_token } = req.body;
프론트와 상의 후 변경하도록 하겠습니다.

2023-05-26 00:07 UTC, innichang commented on src/services/userService.js
> +    const kakaoName = kakaoResult.data.properties.nickname;
오..... 오늘도 또 배워갑니다..... 배움의 즐거움이란...

2023-05-26 08:34 UTC, kyeongraekim approved these changes
LGTM!~

2023-05-26 08:34 UTC, kyeongraekim approved these changes
LGTM!~

2023-05-26 08:34 UTC, kyeongraekim approved these changes
LGTM!~

2023-05-26 08:34 UTC, merged