[45기 이지은] kakao payment
wecode-bootcamp-korea/45-2nd-headbanger-backend pull request #16
Opened 2023-05-27 21:05 UTC by Geun9

## 1. 본 PR이 우리 팀의 웹 서비스 제품성에 어떠한 기여를 하였고, 사용자에게 어떠한 기대효과를 전달하는지 작성해주세요.
- 내 PR이 Merge 됨으로써 유저에게 전달되는 편익/기대효과는 무엇일까요?

  결제 과정에서 신용정보를 입력하는 과정에 번거로움이 있어 유저에게 불편함을 줄 수 있습니다. 이를 방지하기 위해 사이트 결제 방법을 카카오 페이로 지정하여 보다 간편하게 결제할 수 있게 개발하여 유저의 이탈을 줄였습니다.

<br />

## 2. 이 브랜치에서 어떤 내용을 개발했는지 큰 제목과 그리고 상세 내역을 적어주세요.

**카카오 페이 기능**

- header에 userToken과 그 외 필요한 정보를 body에 담아서 request 받음
- 카카오 API를 사용하여 결제 승인 요청을 함
- 카카오 API에서 받은 response와 Front에서 전달 받은 user, product 정보를 DB에 저장
- Front로 유저에게 노출 시킬 결제 정보를 전달

<br />

## 3. 개발한 화면을 캡쳐해서 첨부 해 주세요. (drag & drop 또는 첨부파일 추가)
<br />

-

<br />

## 4. 이 브랜치에서 개발하면서 느꼇던 개발 성장포인트를 적어주세요.

- 카카오 페이에 대한 flow를 공부하게 되었습니다.
> 1. **`Front > kakao`**: 결제 요청
> 2. **`kakao > Front`**: 결제 요청에 대한 response
> 3. **`Front > Back`**: 결제 승인에 필요한 data 전달 (tid, pg_token)
> 4. **`Back > kakao`**: 결제 승인 요청
> 5. **`kakao > Back`**: 결제 승인 요청에 대한 response
> 6. **`Back > Front`**: 유저에게 노출되는 결제 완료 페이지에 필요한 정보 전달

  <br />

2023-05-30 13:30 UTC, kyeongraekim requested changes

2023-05-30 13:30 UTC, kyeongraekim commented on src/models/paymentDao.js
> +});
- 해당 enum은 다른 enum들과 같이 관리할수 있게 위치를 변경해주세요!

2023-05-30 13:30 UTC, kyeongraekim commented on src/services/paymentService.js
> +
- 아직 미완성의 로직 기능이실까요?

2023-05-30 14:30 UTC, Geun9 commented on src/services/paymentService.js
> +
네! Front와 통신 후 에러 핸들링 예정입니다~ :)

2023-05-31 09:59 UTC, kyeongraekim requested changes

2023-05-31 09:59 UTC, kyeongraekim commented on src/controllers/paymentController.js
> +  const todayDate = year + '-' + month + '-' + day
```suggestion

  const today = new Date();
  const todayDate = today.toISOString().split('T')[0];
```

2023-05-31 09:59 UTC, kyeongraekim commented on src/controllers/paymentController.js
> +  const todayDate = year + '-' + month + '-' + day
위와 같이 바꾸어보세요!

2023-06-01 01:54 UTC, kyeongraekim approved these changes
LGTM!~

2023-06-01 01:55 UTC, kyeongraekim commented
이후에 외부 API 활용에 대한 유닛테스트도 도전해보세요!

2023-06-01 01:55 UTC, merged